services:
  app:
    build: .
    container_name: threads
    image: application:v1
    ports:
      - 3000:3000
      - 9229:9229 # for debugging
    volumes:
      - .:/usr/workdir/threads
      - /usr/workdir/node_modules
    command: yarn dev
    environment:
      - PORT = 3000
      - DEPLOYMENT = production
      - NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY = pk_test_cHJvdmVuLWNvcmFsLTY2LmNsZXJrLmFjY291bnRzLmRldiQ
      - CLERK_SECRET_KEY = sk_test_Fq9IGTjik6rXh0bPGpKD4fYutQuDAxWpsP0uJyTREa
      - NEXT_PUBLIC_CLERK_SIGN_IN_URL = /sign-in
      - NEXT_PUBLIC_CLERK_SIGN_UP_URL = /sign-up
      - NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL = /
      - NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL = /onboarding
